// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-25EeGFhDgqSKEuhwIbdlC6zo5jJFWFg',
    appId: '1:430161966794:web:eaf9216d5566665c8e6633',
    messagingSenderId: '430161966794',
    projectId: 'immunosphere2',
    authDomain: 'immunosphere2.firebaseapp.com',
    storageBucket: 'immunosphere2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCruei11qj04IwhVzk-mAWUFN-N3FDWZR0',
    appId: '1:430161966794:android:98e2914d0aa884d98e6633',
    messagingSenderId: '430161966794',
    projectId: 'immunosphere2',
    storageBucket: 'immunosphere2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7uSX0wKxGoYnB1GGBY6IvCV7mL7nGsk',
    appId: '1:430161966794:ios:16d6f7685a4189ac8e6633',
    messagingSenderId: '430161966794',
    projectId: 'immunosphere2',
    storageBucket: 'immunosphere2.firebasestorage.app',
    iosBundleId: 'com.example.immunosphere2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe7uSX0wKxGoYnB1GGBY6IvCV7mL7nGsk',
    appId: '1:430161966794:ios:16d6f7685a4189ac8e6633',
    messagingSenderId: '430161966794',
    projectId: 'immunosphere2',
    storageBucket: 'immunosphere2.firebasestorage.app',
    iosBundleId: 'com.example.immunosphere2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-25EeGFhDgqSKEuhwIbdlC6zo5jJFWFg',
    appId: '1:430161966794:web:20418b6fab3f3eaa8e6633',
    messagingSenderId: '430161966794',
    projectId: 'immunosphere2',
    authDomain: 'immunosphere2.firebaseapp.com',
    storageBucket: 'immunosphere2.firebasestorage.app',
  );
}
