// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC32KGXBi9kNzRiqY3u5ukqE6-R4BVhg8M',
    appId: '1:703110380512:web:4f3df178c3d7975e590985',
    messagingSenderId: '703110380512',
    projectId: 'fypp-25bac',
    authDomain: 'fypp-25bac.firebaseapp.com',
    storageBucket: 'fypp-25bac.firebasestorage.app',
    measurementId: 'G-7KQ04K3PNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4TwnKgwW9-dR03HNAITbxjJLApBShT1c',
    appId: '1:703110380512:android:b68717a755d85cfc590985',
    messagingSenderId: '703110380512',
    projectId: 'fypp-25bac',
    storageBucket: 'fypp-25bac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUC_HcijfjUgDJ5B8SN6jjRf8cxgkChGA',
    appId: '1:703110380512:ios:34d738106350a33e590985',
    messagingSenderId: '703110380512',
    projectId: 'fypp-25bac',
    storageBucket: 'fypp-25bac.firebasestorage.app',
    iosClientId: '703110380512-6a8kijqdl7uvmqjarmhnll9kjt1hptdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUC_HcijfjUgDJ5B8SN6jjRf8cxgkChGA',
    appId: '1:703110380512:ios:34d738106350a33e590985',
    messagingSenderId: '703110380512',
    projectId: 'fypp-25bac',
    storageBucket: 'fypp-25bac.firebasestorage.app',
    iosClientId: '703110380512-6a8kijqdl7uvmqjarmhnll9kjt1hptdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC32KGXBi9kNzRiqY3u5ukqE6-R4BVhg8M',
    appId: '1:703110380512:web:ba17b77c49ba10c1590985',
    messagingSenderId: '703110380512',
    projectId: 'fypp-25bac',
    authDomain: 'fypp-25bac.firebaseapp.com',
    storageBucket: 'fypp-25bac.firebasestorage.app',
    measurementId: 'G-XZXS4TTMJR',
  );
}
